import type { SliderDef } from "./types"

export const CARD_GROUPS: { id: string; label: string; sliders: SliderDef[] }[] = [
  {
    id: "hero-card",
    label: "Hero Card",
    sliders: [
      { label: "Appear Point", path: "sections.0.scrollRange.0", min: 0, max: 0.5, step: 0.01 },
      { label: "Exit Point", path: "sections.0.scrollRange.1", min: 0.05, max: 0.8, step: 0.01 },
      { label: "Slide-up Time", path: "firstSectionAnimation.y.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Slide-up Distance", path: "firstSectionAnimation.y.exitValue", min: -20, max: 0, step: 1 },
      { label: "Zoom Time", path: "firstSectionAnimation.scale.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Start Scale", path: "firstSectionAnimation.scale.startValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Peak Scale", path: "firstSectionAnimation.scale.midValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "End Scale", path: "firstSectionAnimation.scale.exitValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Fade-in Time", path: "firstSectionAnimation.opacity.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Start Opacity", path: "firstSectionAnimation.opacity.startValue", min: 0, max: 1, step: 0.1 },
      { label: "End Opacity", path: "firstSectionAnimation.opacity.exitValue", min: 0, max: 1, step: 0.1 },
      { label: "Blur Start", path: "firstSectionAnimation.blur.startOffset", min: 0, max: 0.3, step: 0.01 },
      { label: "Max Blur", path: "firstSectionAnimation.blur.maxValue", min: 0, max: 20, step: 1 },
      { label: "Round Start", path: "firstSectionAnimation.borderRadius.startOffset", min: 0, max: 0.2, step: 0.01 },
      { label: "Round End", path: "firstSectionAnimation.borderRadius.endOffset", min: 0.01, max: 0.3, step: 0.01 },
      { label: "Start Radius", path: "firstSectionAnimation.borderRadius.startValue", min: 0, max: 64, step: 1 },
      { label: "End Radius", path: "firstSectionAnimation.borderRadius.endValue", min: 0, max: 64, step: 1 },
    ],
  },
  {
    id: "problem-card",
    label: "Problem Card",
    sliders: [
      { label: "Appear Point", path: "sections.1.scrollRange.0", min: 0, max: 0.5, step: 0.01 },
      { label: "Exit Point", path: "sections.1.scrollRange.1", min: 0.1, max: 0.8, step: 0.01 },
      { label: "Slide-up Time", path: "middleSectionAnimation.y.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Exit Delay", path: "middleSectionAnimation.y.exitStartOffset", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Slide-up Distance", path: "middleSectionAnimation.y.exitValue", min: -20, max: 0, step: 1 },
      { label: "Zoom Time", path: "middleSectionAnimation.scale.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Start Scale", path: "middleSectionAnimation.scale.enterValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "End Scale", path: "middleSectionAnimation.scale.exitValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Fade-in Time", path: "middleSectionAnimation.opacity.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "End Opacity", path: "middleSectionAnimation.opacity.exitValue", min: 0, max: 1, step: 0.1 },
      { label: "Blur Fade Point", path: "middleSectionAnimation.blur.endOffset", min: 0.01, max: 0.3, step: 0.01 },
      { label: "Max Blur", path: "middleSectionAnimation.blur.maxValue", min: 0, max: 20, step: 1 },
      { label: "Round Start", path: "middleSectionAnimation.borderRadius.startOffset", min: 0, max: 0.2, step: 0.01 },
      { label: "Round End", path: "middleSectionAnimation.borderRadius.endOffset", min: 0.01, max: 0.3, step: 0.01 },
      { label: "Corner Radius", path: "middleSectionAnimation.borderRadius.value", min: 0, max: 64, step: 1 },
      { label: "Left Sub-card At", path: "sections.1.subAnimations.left.trigger", min: 0.05, max: 0.5, step: 0.01 },
      { label: "Right Sub-card At", path: "sections.1.subAnimations.right.trigger", min: 0.1, max: 0.6, step: 0.01 },
      { label: "Bounce Strength", path: "subAnimationSpring.stiffness", min: 10, max: 300, step: 5 },
      { label: "Bounce Settle", path: "subAnimationSpring.damping", min: 5, max: 50, step: 1 },
    ],
  },
  {
    id: "how-card",
    label: "HowItWorks Card",
    sliders: [
      { label: "Tab 1 Appears At", path: "sections.2.scrollRange.0", min: 0.1, max: 0.8, step: 0.01 },
      { label: "Tab 1 Exits At", path: "sections.2.scrollRange.1", min: 0.3, max: 0.9, step: 0.01 },
      { label: "Tab 2 Appears At", path: "sections.3.scrollRange.0", min: 0.2, max: 0.9, step: 0.01 },
      { label: "Tab 3 Appears At", path: "sections.4.scrollRange.0", min: 0.3, max: 0.9, step: 0.01 },
    ],
  },
  {
    id: "cta-card",
    label: "CTA Card",
    sliders: [
      { label: "Appear Point", path: "sections.5.scrollRange.0", min: 0.5, max: 0.95, step: 0.01 },
      { label: "Exit Point", path: "sections.5.scrollRange.1", min: 0.8, max: 1.0, step: 0.01 },
      { label: "Slide-up Time", path: "lastSectionAnimation.y.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Zoom Time", path: "lastSectionAnimation.scale.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Start Scale", path: "lastSectionAnimation.scale.enterValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Fade-in Time", path: "lastSectionAnimation.opacity.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Max Blur", path: "lastSectionAnimation.blur.maxValue", min: 0, max: 20, step: 1 },
      { label: "Corner Radius", path: "lastSectionAnimation.borderRadius.value", min: 0, max: 64, step: 1 },
    ],
  },
  {
    id: "global-card",
    label: "Global",
    sliders: [
      { label: "Scroll Length", path: "scrollHeightVH", min: 200, max: 1000, step: 10, unit: "vh" },
      { label: "Scroll Smoothness", path: "spring.stiffness", min: 10, max: 300, step: 5 },
      { label: "Scroll Settle", path: "spring.damping", min: 5, max: 50, step: 1 },
      { label: "Rest Threshold", path: "spring.restDelta", min: 0.0001, max: 0.01, step: 0.0001 },
      { label: "Pre-load Margin", path: "lazyMountMargin", min: 0, max: 0.5, step: 0.05 },
      { label: "Glow Checkpoint 1", path: "bgGlowOpacity.input.0", min: 0, max: 0.5, step: 0.01 },
      { label: "Glow Opacity 1", path: "bgGlowOpacity.output.0", min: 0, max: 1, step: 0.05 },
      { label: "Glow Checkpoint 2", path: "bgGlowOpacity.input.1", min: 0, max: 0.5, step: 0.01 },
      { label: "Glow Opacity 2", path: "bgGlowOpacity.output.1", min: 0, max: 1, step: 0.05 },
      { label: "Glow Checkpoint 3", path: "bgGlowOpacity.input.2", min: 0.1, max: 0.8, step: 0.01 },
      { label: "Glow Opacity 3", path: "bgGlowOpacity.output.2", min: 0, max: 1, step: 0.05 },
      { label: "Glow Checkpoint 4", path: "bgGlowOpacity.input.3", min: 0.5, max: 0.95, step: 0.01 },
      { label: "Glow Opacity 4", path: "bgGlowOpacity.output.3", min: 0, max: 1, step: 0.05 },
      { label: "Glow Checkpoint 5", path: "bgGlowOpacity.input.4", min: 0.7, max: 1, step: 0.01 },
      { label: "Glow Opacity 5", path: "bgGlowOpacity.output.4", min: 0, max: 1, step: 0.05 },
    ],
  },
]
