import type { SliderDef } from "./types"

export const GROUPS: { id: string; label: string; sliders: SliderDef[] }[] = [
  {
    id: "timing",
    label: "Section Timing",
    sliders: [
      { label: "Hero Start", path: "sections.0.scrollRange.0", min: 0, max: 0.5, step: 0.01 },
      { label: "Hero End", path: "sections.0.scrollRange.1", min: 0.05, max: 0.8, step: 0.01 },
      { label: "Problem Start", path: "sections.1.scrollRange.0", min: 0, max: 0.5, step: 0.01 },
      { label: "Problem End", path: "sections.1.scrollRange.1", min: 0.1, max: 0.8, step: 0.01 },
      { label: "HowItWorks Start", path: "sections.2.scrollRange.0", min: 0.1, max: 0.8, step: 0.01 },
      { label: "HowItWorks End", path: "sections.2.scrollRange.1", min: 0.3, max: 0.9, step: 0.01 },
      { label: "Tab 2 Start", path: "sections.3.scrollRange.0", min: 0.2, max: 0.9, step: 0.01 },
      { label: "Tab 3 Start", path: "sections.4.scrollRange.0", min: 0.3, max: 0.9, step: 0.01 },
      { label: "CTA Start", path: "sections.5.scrollRange.0", min: 0.5, max: 0.95, step: 0.01 },
      { label: "CTA End", path: "sections.5.scrollRange.1", min: 0.8, max: 1.0, step: 0.01 },
    ],
  },
  {
    id: "global",
    label: "Global",
    sliders: [
      { label: "Scroll Height", path: "scrollHeightVH", min: 200, max: 1000, step: 10, unit: "vh" },
      { label: "Spring Stiffness", path: "spring.stiffness", min: 10, max: 300, step: 5 },
      { label: "Spring Damping", path: "spring.damping", min: 5, max: 50, step: 1 },
      { label: "Spring Rest Delta", path: "spring.restDelta", min: 0.0001, max: 0.01, step: 0.0001 },
      { label: "Lazy Mount Margin", path: "lazyMountMargin", min: 0, max: 0.5, step: 0.05 },
    ],
  },
  {
    id: "hero",
    label: "Hero Animation",
    sliders: [
      { label: "Y Enter Duration", path: "firstSectionAnimation.y.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Y Exit Value (vh)", path: "firstSectionAnimation.y.exitValue", min: -20, max: 0, step: 1 },
      { label: "Scale Enter Duration", path: "firstSectionAnimation.scale.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Scale Start", path: "firstSectionAnimation.scale.startValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Scale Mid", path: "firstSectionAnimation.scale.midValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Scale Exit", path: "firstSectionAnimation.scale.exitValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Opacity Enter Duration", path: "firstSectionAnimation.opacity.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Opacity Start", path: "firstSectionAnimation.opacity.startValue", min: 0, max: 1, step: 0.1 },
      { label: "Opacity Exit", path: "firstSectionAnimation.opacity.exitValue", min: 0, max: 1, step: 0.1 },
      { label: "Blur Start Offset", path: "firstSectionAnimation.blur.startOffset", min: 0, max: 0.3, step: 0.01 },
      { label: "Blur Max", path: "firstSectionAnimation.blur.maxValue", min: 0, max: 20, step: 1 },
      { label: "Radius Start Offset", path: "firstSectionAnimation.borderRadius.startOffset", min: 0, max: 0.2, step: 0.01 },
      { label: "Radius End Offset", path: "firstSectionAnimation.borderRadius.endOffset", min: 0.01, max: 0.3, step: 0.01 },
      { label: "Radius Start (px)", path: "firstSectionAnimation.borderRadius.startValue", min: 0, max: 64, step: 1 },
      { label: "Radius End (px)", path: "firstSectionAnimation.borderRadius.endValue", min: 0, max: 64, step: 1 },
    ],
  },
  {
    id: "card",
    label: "Card Animation",
    sliders: [
      { label: "Y Enter Duration", path: "middleSectionAnimation.y.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Y Exit Start Offset", path: "middleSectionAnimation.y.exitStartOffset", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Y Exit Value (vh)", path: "middleSectionAnimation.y.exitValue", min: -20, max: 0, step: 1 },
      { label: "Scale Enter Duration", path: "middleSectionAnimation.scale.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Scale Enter", path: "middleSectionAnimation.scale.enterValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Scale Exit", path: "middleSectionAnimation.scale.exitValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Opacity Enter Duration", path: "middleSectionAnimation.opacity.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Opacity Exit", path: "middleSectionAnimation.opacity.exitValue", min: 0, max: 1, step: 0.1 },
      { label: "Blur End Offset", path: "middleSectionAnimation.blur.endOffset", min: 0.01, max: 0.3, step: 0.01 },
      { label: "Blur Max", path: "middleSectionAnimation.blur.maxValue", min: 0, max: 20, step: 1 },
      { label: "Radius Start Offset", path: "middleSectionAnimation.borderRadius.startOffset", min: 0, max: 0.2, step: 0.01 },
      { label: "Radius End Offset", path: "middleSectionAnimation.borderRadius.endOffset", min: 0.01, max: 0.3, step: 0.01 },
      { label: "Radius (px)", path: "middleSectionAnimation.borderRadius.value", min: 0, max: 64, step: 1 },
    ],
  },
  {
    id: "sub",
    label: "Sub-Animations",
    sliders: [
      { label: "Left Card Slide-in Point", path: "sections.1.subAnimations.left.trigger", min: 0.05, max: 0.5, step: 0.01 },
      { label: "Right Card Slide-in Point", path: "sections.1.subAnimations.right.trigger", min: 0.1, max: 0.6, step: 0.01 },
      { label: "Sub-card Spring Stiffness", path: "subAnimationSpring.stiffness", min: 10, max: 300, step: 5 },
      { label: "Sub-card Spring Damping", path: "subAnimationSpring.damping", min: 5, max: 50, step: 1 },
    ],
  },
  {
    id: "bg",
    label: "Background Glow",
    sliders: [
      { label: "Glow Point 1", path: "bgGlowOpacity.input.0", min: 0, max: 0.5, step: 0.01 },
      { label: "Opacity 1", path: "bgGlowOpacity.output.0", min: 0, max: 1, step: 0.05 },
      { label: "Glow Point 2", path: "bgGlowOpacity.input.1", min: 0, max: 0.5, step: 0.01 },
      { label: "Opacity 2", path: "bgGlowOpacity.output.1", min: 0, max: 1, step: 0.05 },
      { label: "Glow Point 3", path: "bgGlowOpacity.input.2", min: 0.1, max: 0.8, step: 0.01 },
      { label: "Opacity 3", path: "bgGlowOpacity.output.2", min: 0, max: 1, step: 0.05 },
      { label: "Glow Point 4", path: "bgGlowOpacity.input.3", min: 0.5, max: 0.95, step: 0.01 },
      { label: "Opacity 4", path: "bgGlowOpacity.output.3", min: 0, max: 1, step: 0.05 },
      { label: "Glow Point 5", path: "bgGlowOpacity.input.4", min: 0.7, max: 1, step: 0.01 },
      { label: "Opacity 5", path: "bgGlowOpacity.output.4", min: 0, max: 1, step: 0.05 },
    ],
  },
  {
    id: "cta",
    label: "CTA Animation",
    sliders: [
      { label: "Y Enter Duration", path: "lastSectionAnimation.y.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Scale Enter Duration", path: "lastSectionAnimation.scale.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Scale Enter", path: "lastSectionAnimation.scale.enterValue", min: 0.5, max: 1.5, step: 0.01 },
      { label: "Opacity Enter Duration", path: "lastSectionAnimation.opacity.enterDuration", min: 0.01, max: 0.25, step: 0.01 },
      { label: "Blur Max", path: "lastSectionAnimation.blur.maxValue", min: 0, max: 20, step: 1 },
      { label: "Radius (px)", path: "lastSectionAnimation.borderRadius.value", min: 0, max: 64, step: 1 },
    ],
  },
]
